# Generated by Django 2.1.5 on 2020-05-30 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0003_remove_tag_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=50, verbose_name='目前状态')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('category', models.CharField(choices=[('F', '拾到物品'), ('L', '丢失物品')], default='Found Item', max_length=1, verbose_name='类别')),
                ('location', models.CharField(max_length=50, verbose_name='地点')),
                ('phone_number', models.CharField(max_length=16, verbose_name='手机号码')),
                ('mail_address', models.CharField(default='', max_length=50, verbose_name='Email地址')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='图片')),
                ('identification_mark', models.TextField(blank=True, verbose_name='具体信息')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('tmp_slug', models.CharField(default='', max_length=30)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.Tag', verbose_name='标签')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'ordering': ['-update'],
            },
        ),
    ]
