# Generated by Django 3.0.4 on 2020-05-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tmp_slug',
            field=models.CharField(default='', max_length=30),
        ),
    ]
