# Generated by Django 2.1.5 on 2020-05-30 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='secret_information',
            field=models.TextField(blank=True, help_text='Separate each item by comma'),
        ),
    ]
