# Generated by Django 2.1.5 on 2020-05-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_tmp_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='mail_address',
            field=models.CharField(default='', max_length=50),
        ),
    ]
