# Generated by Django 3.0.4 on 2020-04-22 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
