# Generated by Django 2.1.5 on 2020-05-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_mail_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='identification_mark',
            field=models.TextField(blank=True, help_text='Separate each item by comma'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='secret_information',
            field=models.TextField(blank=True, help_text='Separate each item by comma'),
        ),
    ]
