# Generated by Django 3.0.4 on 2020-05-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20200523_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tmp_slug',
        ),
    ]
