# Generated by Django 3.0.4 on 2020-05-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_remove_item_tmp_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tmp_slug',
            field=models.CharField(default='', max_length=30),
        ),
    ]
