# Generated by Django 2.1.5 on 2020-05-25 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_item_tmp_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('F', 'Found Item'), ('L', 'Lost Item')], default='Found Item', max_length=1, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='item',
            name='identification_mark',
            field=models.TextField(blank=True, help_text='Separate each item by comma', verbose_name='具体信息'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(blank=True, upload_to='', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(max_length=50, verbose_name='地点'),
        ),
        migrations.AlterField(
            model_name='item',
            name='mail_address',
            field=models.CharField(default='', max_length=50, verbose_name='Email地址'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='item',
            name='phone_number',
            field=models.CharField(max_length=16, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(max_length=50, verbose_name='目前状态'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.Tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
    ]
