# Generated by Django 2.1.5 on 2020-05-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20200525_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('F', '拾到物品'), ('L', '丢失物品')], default='Found Item', max_length=1, verbose_name='类别'),
        ),
    ]
