# Generated by Django 2.1.5 on 2020-05-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_remove_item_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='secret_information',
        ),
        migrations.AlterField(
            model_name='item',
            name='identification_mark',
            field=models.TextField(blank=True, verbose_name='具体信息'),
        ),
    ]
