# Generated by Django 3.0.4 on 2020-05-25 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
