# Generated by Django 3.0.4 on 2020-05-25 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200523_1420'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reward',
        ),
    ]
