# Generated by Django 2.1.5 on 2020-05-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='电话号码'),
        ),
    ]
