# Generated by Django 3.0.4 on 2020-04-23 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemreplaycomment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemreplaycomment',
            name='reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='comment.ItemComment'),
        ),
        migrations.AddField(
            model_name='itemcomment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
