# Generated by Django 3.0.4 on 2020-04-23 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment', '0002_auto_20200423_1835'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcomment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='item.Item'),
        ),
    ]
